#!/bin/bash
#
# Copyright (C) 2018 Pawel Krupa (@paulfantom) - All Rights Reserved
# Permission to copy and modify is granted under the MIT license
#
# Script to automatically update latest available version of prometheus stack
#
# Requirements:
#   - GH_TOKEN variable set with GitHub token. Access level: repo.public_repo
#   - docker

set -e
function cleanup {
  rm -rf "/tmp/ansible-$TARGET"
}
trap cleanup EXIT

if [ "${GH_TOKEN}" == "" ]; then
	echo "GitHub token not set. Exiting..."
	exit 1
fi

ORGANIZATION=${ORGANIZATION:-prometheus}
TARGET=${TARGET:-prometheus}
GIT_MAIL="cloudalchemybot@gmail.com"
GIT_USER="cloudalchemybot"

PR_TITLE="Upgrade to latest release of $TARGET"
PR_MSG="This is an autogenerated pull request. Please review changelogs of new application version. CC: @pkrupa, @rdemachkovych"

LINK="https://api.github.com/repos/$ORGANIZATION/$TARGET/releases/latest"
VERSION=$(curl "$LINK" 2>/dev/null | jq -r '.tag_name' | sed 's/^v//')
[ "$VERSION" == "" ] && exit 1

git clone --depth=1 "https://github.com/cloudalchemy/ansible-$TARGET.git" "/tmp/ansible-$TARGET"
cd "/tmp/ansible-$TARGET" || exit 1
CURR="$(grep "_version" defaults/main.yml | awk -F ': ' '{print $2}')"

if [ "${CURR}" == "${VERSION}" ]; then
    echo "Latest version already commited"
else
	git config user.email "${GIT_MAIL}"
    git config user.name "${GIT_USER}"
    git remote rm origin
    git remote add origin "https://${GIT_USER}:${GH_TOKEN}@github.com/cloudalchemy/ansible-$TARGET.git" &>/dev/null
    git checkout -b "release_$VERSION"
    sed -i "s/_version: $CURR/_version: $VERSION/" defaults/main.yml
    git add defaults/main.yml
    git commit -m "bump version to $VERSION"
    git push --set-upstream origin "release_$VERSION" &>/dev/null
    curl -H "Authorization: token ${GH_TOKEN}" \
    	 -X POST "https://api.github.com/repos/cloudalchemy/ansible-$TARGET/pulls" \
    	 -d "{\"title\": \"${PR_TITLE}\", \"head\": \"release_$VERSION\", \"body\": \"${PR_MSG}\", \"base\": \"master\"}" \
    	 &>/dev/null || echo "Couldn't create Pull Request"
fi
